name: Publish project

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs: {}

jobs:
  publish:

    name: Publish to GitHub Packages and the 'maven-repository' branch
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    # Setup environment
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 15
        distribution: adopt
    - name: Set up cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: "gradle-\
          ${{runner.os}}-\
          ${{hashFiles('gradle/wrapper/gradle-wrapper.properties')}}-\
          ${{hashFiles('**/*.gradle')}}"
    # Build and publish
    - name: Build project
      id: gradle-build
      run: ./gradlew --stacktrace assemble writeMetadata
    - name: Clone 'maven-repository' branch
      uses: actions/checkout@v2
      with:
        ref: refs/heads/maven-repository
        path: build/maven-repository
    - name: Publish project
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew --stacktrace publish
    - name: Push 'maven-repository' branch
      run: |
        git add -A
        git \
          -c "user.name=github-actions[bot]" \
          -c "user.email=41898282+github-actions[bot]@users.noreply.github.com" \
          commit -m "Publish $(cat ../metadata/version.txt)"
        git push origin 'HEAD:refs/heads/maven-repository'
      working-directory: build/maven-repository
    # Upload build reports
    - name: Upload build reports
      if: steps.gradle-build.outcome == 'success' || steps.gradle-build.outcome == 'failure'
      uses: actions/upload-artifact@v2
      with:
        name: build-reports
        path: build/reports/
        if-no-files-found: ignore
